language: python

python:
  - "3.12"

jobs:
  include:
    - env: DJANGO_SPEC='Django>=4.2,<5.0'
    - env: DJANGO_SPEC='Django>=5.0,<6.0'
    - env: DJANGO_SPEC='Django>=6.0,<7.0'

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install "$DJANGO_SPEC"

script:
  - python sampleproject/manage.py check
  - python leavedemo/manage.py check

